-- CreateTable configurador_operacional
CREATE TABLE "configurador_operacional" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "corPrevidenciario" TEXT NOT NULL DEFAULT '#3B82F6',
    "corTrabalhista" TEXT NOT NULL DEFAULT '#10B981',
    "corCivil" TEXT NOT NULL DEFAULT '#F59E0B',
    "corFamilia" TEXT NOT NULL DEFAULT '#EC4899',
    "corTributario" TEXT NOT NULL DEFAULT '#8B5CF6',
    "corNovoColuna" TEXT NOT NULL DEFAULT '#6B7280',
    "corTriagemColuna" TEXT NOT NULL DEFAULT '#3B82F6',
    "corAndamentoColuna" TEXT NOT NULL DEFAULT '#F59E0B',
    "corConcluidoColuna" TEXT NOT NULL DEFAULT '#10B981',
    "labelNovo" TEXT NOT NULL DEFAULT 'Novo',
    "labelTriagem" TEXT NOT NULL DEFAULT 'Triagem',
    "labelAndamento" TEXT NOT NULL DEFAULT 'Andamento',
    "labelConcluido" TEXT NOT NULL DEFAULT 'Concluído',
    "corBaixa" TEXT NOT NULL DEFAULT '#10B981',
    "corNormal" TEXT NOT NULL DEFAULT '#3B82F6',
    "corAlta" TEXT NOT NULL DEFAULT '#F59E0B',
    "corUrgente" TEXT NOT NULL DEFAULT '#EF4444',
    "tema" TEXT NOT NULL DEFAULT 'light',
    "tamanhoCard" TEXT NOT NULL DEFAULT 'medium',
    "mostrarAvatar" BOOLEAN NOT NULL DEFAULT true,
    "mostrarProcesso" BOOLEAN NOT NULL DEFAULT true,
    "mostrarDPP" BOOLEAN NOT NULL DEFAULT true,
    "mostrarAlertas" BOOLEAN NOT NULL DEFAULT true,
    "mostrarObservacoes" BOOLEAN NOT NULL DEFAULT true,
    "colunaNovoVisivel" BOOLEAN NOT NULL DEFAULT true,
    "colunaTriagemVisivel" BOOLEAN NOT NULL DEFAULT true,
    "colunaAndamentoVisivel" BOOLEAN NOT NULL DEFAULT true,
    "colunaConcluidoVisivel" BOOLEAN NOT NULL DEFAULT true,
    "filtroAreaPadrao" TEXT,
    "filtroNaturezaPadrao" TEXT,
    "filtroResponsavelPadrao" TEXT,
    "registrosPorPagina" INTEGER NOT NULL DEFAULT 50,
    "autoRefreshStats" INTEGER NOT NULL DEFAULT 30,
    "mostrarStatsPorColuna" BOOLEAN NOT NULL DEFAULT true,
    "requererMotivoMovimento" BOOLEAN NOT NULL DEFAULT false,
    "bloqueioAutomatico" BOOLEAN NOT NULL DEFAULT true,
    "notificacoes" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "configurador_operacional_pkey" PRIMARY KEY ("id")
);
